-- ============================================================================
-- RevolutionMedia-AI · Seed admin (NO-OP)
-- ----------------------------------------------------------------------------
-- ponytail: SEC-001 — the prior version inserted a hardcoded admin hash
-- (SHA-256 of a known plaintext password). That literal is a leak
-- vector: anyone with source access can log in as admin on a fresh
-- deploy. The literal has been removed.
--
-- The bootstrap admin is now created exclusively by start.sh, which
-- reads BOOTSTRAP_ADMIN_PASSWORD from the environment and SHA-256
-- hashes it before INSERT. That keeps the credential out of the repo
-- and out of the migration file.
--
-- This migration is kept as a no-op for backward compatibility with
-- deployment pipelines that still list it in the migrations glob. New
-- admins are created via the env-driven path in start.sh; existing
-- admins seeded by an older version of this file are NOT touched by
-- this no-op.
-- ============================================================================

SELECT 1;
