"""Caller confirmation gate for call_transfer tools.

Why this exists
---------------
A `call_transfer` tool ends the backend's participation in the call.
`execute_call_transfer` issues `calls.update(twiml=<Dial>...)`, which takes
the caller out of our WebSocket: the agent loses the audio AND the
conversation context, and there is no way back. It is the single most
irreversible thing this product does.

Until now the ONLY thing standing between the model and that <Dial> was
the prompt section generated by agent_prompt_tools. A prompt is not a
control. Production evidence (2026-10-06): with `tool_choice=auto` and 3
tools registered, `gpt-realtime` emitted a `call_transfer` tool call on
its own, mid-conversation, and the caller was transferred to a
recruiter's number without ever asking for one.

The gate
--------
When the model asks to transfer, we do NOT transfer. We:

  1. park the request on the session (`pending_transfer`) with an expiry,
  2. speak a short confirmation question naming the department,
  3. resolve the answer on the caller's NEXT turn.

  * confirmed -> transfer, and we do it directly, without asking the
    model again (it already asked; re-asking invites a second,
    contradictory decision).
  * denied -> drop it and let the conversation continue.
  * anything else, or the expiry passing -> drop it silently. In a phone
    call an unanswered question must not become a transfer.

Design notes
------------
  * Deliberately does NOT ask the model whether the caller confirmed. The
    model is the thing we are guarding against; a second opinion from it
    is not a control. The backend decides from the transcript.
  * Per-tool opt-out via `require_confirmation`. Default is ON for
    call_transfer, so an operator has to actively disable it for a
    destination they trust. Fail-safe direction.
  * The parked state holds only what the transfer needs (tool id, name,
    destination, ring timeout, chain) — no credentials.
"""
from __future__ import annotations

import logging
import time

log = logging.getLogger("stt_server.transfer_confirmation")


# A phone caller who was just asked "shall I transfer you?" answers in
# one or two words. Anything longer is a new question, not an answer, so
# it must NOT confirm.
DEFAULT_PENDING_TTL_SEC = 25.0

# ponytail: matched on the NORMALISED, accent-stripped, lowercased
# transcript, so "Sí", "si", "sí" and "SI" all behave the same. Kept
# short on purpose: a loose matcher here transfers people who did not
# agree.
_AFFIRMATIVE = {
    "si", "sí", "claro", "dale", "va", "venga", "ok", "okay", "de acuerdo",
    "correcto", "exacto", "perfecto", "yes", "yeah", "yep", "sure", "go ahead",
    "adelante", "confirmo", "confirmar", "hazlo", "hagalo", "de acuerdo",
    "por favor", "porfavor", "transfiereme", "transfereme", "pasame",
    "con gusto", "esta bien", "está bien", "me interesa", "interesa",
}

_NEGATIVE = {
    "no", "nel", "nop", "nada", "cancela", "cancela", "cancelar", "olvidalo",
    "olvídalo", "no gracias", "no por favor", "nonop", "negative", "stop",
    "detente", "para", "quieto", "no me interesa", "no gracias",
}

# Explicitly unresolved: the caller is answering something else. Treating
# these as "not confirmed" matters because a caller saying "no, ¿a qué
# hora abren?" has NOT agreed to a transfer.
_UNRESOLVED = {
    "si no", "no se", "no se cuando", "mas tarde", "más tarde", "ahora no",
    "despues", "después", "lo pienso", "te llamo", "lo consulto",
}


def normalize(text: str | None) -> str:
    """Lowercase, strip accents and punctuation for intent matching."""
    import unicodedata

    raw = (text or "").strip().lower()
    if not raw:
        return ""
    # Decompose so accents become a separate combining mark, then drop it.
    decomposed = unicodedata.normalize("NFD", raw)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    out = []
    for ch in stripped:
        out.append(" " if (not ch.isalnum() and ch != " ") else ch)
    return " ".join("".join(out).split())


def classify_reply(text: str | None) -> str:
    """Return "confirm" | "deny" | "unresolved"."""
    norm = normalize(text)
    if not norm:
        return "unresolved"
    if norm in _NEGATIVE:
        return "deny"
    if norm in _UNRESOLVED:
        return "unresolved"
    if norm in _AFFIRMATIVE:
        return "confirm"

    # Allow a short lead-in so "¿sí, por favor?" counts, but keep the
    # window tiny: 4 words. "sí claro que sí quiero saber más sobre el
    # puesto" must NOT confirm.
    words = norm.split()
    if len(words) <= 4:
        if any(w in _NEGATIVE for w in words):
            return "deny"
        if any(w in _AFFIRMATIVE for w in words):
            return "confirm"
    # A question is never a confirmation.
    if "?" in (text or "") or norm.endswith("?"):
        return "unresolved"
    return "unresolved"


def should_confirm(tool_def: dict | None) -> bool:
    """Does this transfer tool need the caller's explicit yes?

    Default ON. Only an explicit `require_confirmation=False` opts out, so
    a tool row written before this feature existed (column NULL) is
    treated the safe way.
    """
    if not tool_def:
        return True
    raw = tool_def.get("require_confirmation")
    if raw is None:
        return True
    if isinstance(raw, str):
        return raw.strip().lower() not in {"false", "0", "no", "off"}
    return bool(raw)


def park(session, tool_def: dict, *, ttl_sec: float = DEFAULT_PENDING_TTL_SEC) -> dict:
    """Remember a transfer the model asked for, without performing it.

    Returns the parked dict so the caller can log it.
    """
    pending = {
        "tool_id": tool_def.get("id"),
        "tool_name": tool_def.get("name") or tool_def.get("function_name") or "",
        "destination": tool_def.get("destination") or "",
        "ring_timeout_sec": tool_def.get("ring_timeout_sec"),
        "chain": getattr(session, "transfer_chain", None),
        "expires_at": time.monotonic() + max(5.0, float(ttl_sec)),
        "parked_at": time.monotonic(),
    }
    session.pending_transfer = pending
    log.info(
        "[TRANSFER_CONFIRM] parked tool=%s destination=%s ttl=%.0fs session=%s",
        pending["tool_name"], pending["destination"], ttl_sec,
        getattr(session, "session_key", "?"),
    )
    return pending


def confirmation_prompt(tool_name: str | None, lang: str = "es") -> str:
    """What the agent says instead of transferring.

    Names the department so the caller knows what they are agreeing to,
    and is a single short sentence — a long prompt here is what makes an
    agent talk over a confused caller.
    """
    who = (tool_name or "").strip() or "un asesor"
    if (lang or "es").lower().startswith("es"):
        return f"¿Deseas que te transfiera con {who}?"
    return f"Would you like me to transfer you to {who}?"


def drop(session, reason: str) -> None:
    pending = getattr(session, "pending_transfer", None)
    if pending is None:
        return
    session.pending_transfer = None
    log.info(
        "[TRANSFER_CONFIRM] dropped tool=%s reason=%s session=%s",
        pending.get("tool_name"), reason,
        getattr(session, "session_key", "?"),
    )


def resolve(session, user_text: str | None) -> tuple[str, dict | None]:
    """Consume the parked transfer against the caller's answer.

    Returns (verdict, pending). verdict is one of:

      "confirmed"  -> transfer, using `pending`
      "denied"     -> drop, conversation continues
      "unresolved" -> KEEP waiting (only inside the TTL)
      "expired"    -> drop
      "none"       -> nothing was parked

    An unresolved answer inside the window deliberately leaves the
    request parked, because the caller is mid-sentence ("sí, pero solo a
    partir de las nueve") and dropping it there would lose a genuine
    confirmation one turn later.
    """
    pending = getattr(session, "pending_transfer", None)
    if not pending:
        return "none", None

    if time.monotonic() > float(pending.get("expires_at") or 0):
        drop(session, "expired")
        return "expired", None

    verdict = classify_reply(user_text)
    if verdict == "confirm":
        session.pending_transfer = None
        log.info(
            "[TRANSFER_CONFIRM] CONFIRMED tool=%s destination=%s session=%s",
            pending.get("tool_name"), pending.get("destination"),
            getattr(session, "session_key", "?"),
        )
        return "confirmed", pending
    if verdict == "deny":
        drop(session, "caller denied")
        return "denied", None
    return "unresolved", pending


def tool_result_for_model(pending: dict | None, lang: str = "es") -> str:
    """What to feed back to the model after intercepting the tool call.

    Two jobs: tell it the transfer did NOT happen, so it cannot claim
    otherwise, and make it actually put the question to the caller. The
    Realtime path relies on the model to speak the question (speaking it
    from here too would stack two voices), so the wording is given to it
    verbatim instead of paraphrased.
    """
    who = (pending or {}).get("tool_name") or "el departamento"
    if (lang or "es").lower().startswith("es"):
        return (
            f"La transferencia a {who} NO se ha realizado y no debes "
            f"realizarla tú. Ahora debes PREGUNTARLE al cliente, con tus "
            f"propias palabras: «¿Deseas que te transfiera con {who}?». "
            f"No digas que ya fue transferido, no lo promises y no vuelvas "
            f"a solicitar la transferencia hasta que el cliente responda."
        )
    return (
        f"The transfer to {who} has NOT happened and you must not perform it "
        f"yourself. Ask the caller now, in your own words: "
        f"“Would you like me to transfer you to {who}?”. Do not say they "
        f"were transferred, do not promise it, and do not request the "
        f"transfer again until the caller answers."
    )