import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / "entornoLocal.env")


# ponytail: the only env vars that remain are deployment infrastructure
# (PORT, PUBLIC_URL, ALLOWED_ORIGINS) and security primitives
# (DATABASE_URL, CREDENTIAL_ENCRYPTION_KEY). Every provider API key,
# model name, and tunable was an env fallback that masked the user's
# actual config — moved to per-user (tools_integrations) or per-agent
# (agents row) tables. If a value isn't set anywhere in the DB, the
# call fails explicitly with a clear log line.

PORT = int(os.environ.get("PORT", 8080))
PUBLIC_URL = os.getenv("PUBLIC_URL")


TWILIO_SR = 8000
TWILIO_CHANNELS = 1
FRAME_DURATION_MS = 20
TWILIO_OUTBOUND_CHUNK_BYTES = 160


# webrtc VAD mode: 0..3 (0 less aggressive, 3 most aggressive). Tunable
# per-deploy but not per-user; this stays in env so an operator can
# dial it without a code change.
WEBRTC_VAD_MODE = int(os.getenv("WEBRTC_VAD_MODE", "1"))


# ponytail: defaults to "es" so a freshly-deployed instance behaves
# like the platform's primary locale. Per-call language still comes
# from the agent's row (session.preferred_language).
DEFAULT_CALL_LANGUAGE = os.getenv("DEFAULT_CALL_LANGUAGE", "es").strip().lower()


# If false, we buffer the full assistant reply and run TTS once per reply.
# This avoids ultra-short TTS segments and reduces the chance of "first words only" failures.
REALTIME_TTS_STREAMING = os.getenv("REALTIME_TTS_STREAMING", "false").strip().lower() in {"1", "true", "yes", "on"}


LOG_TWILIO_PLAYBACK = os.getenv("LOG_TWILIO_PLAYBACK", "false").strip().lower() in {"1", "true", "yes", "on"}
SAVE_TWILIO_FRAMES = os.getenv("SAVE_TWILIO_FRAMES", "false").strip().lower() in {"1", "true", "yes", "on"}
FILLER_TTS_ENABLED = os.getenv("FILLER_TTS_ENABLED", "true").strip().lower() in {"1", "true", "yes", "on"}
ENABLE_DEBUG_ENDPOINTS = os.getenv("ENABLE_DEBUG_ENDPOINTS", "false").strip().lower() in {"1", "true", "yes", "on"}
# ponytail: L2 from the call-flow audit. User transcripts can carry
# PII (DNI, credit card, address, name). Default off in production;
# set to true in dev for debugging.
LOG_TRANSCRIPT_CONTENT = os.getenv("LOG_TRANSCRIPT_CONTENT", "false").strip().lower() in {"1", "true", "yes", "on"}

# ponytail: L6 from the call-flow audit. How long playback_loop waits
# for Twilio to send the stream_sid before giving up on the first
# audio item. Bumped from a hardcoded 100 iterations at 50 ms to
# named constants so it's tunable without code diving.
STREAM_SID_WAIT_MAX_MS = int(os.getenv("STREAM_SID_WAIT_MAX_MS", "5000"))
STREAM_SID_WAIT_POLL_MS = int(os.getenv("STREAM_SID_WAIT_POLL_MS", "50"))


STT_AUDIO_QUEUE_MAXSIZE = int(os.getenv("STT_AUDIO_QUEUE_MAXSIZE", "300"))
REALTIME_AUDIO_QUEUE_MAXSIZE = int(os.getenv("REALTIME_AUDIO_QUEUE_MAXSIZE", "300"))
# How many Twilio audio chunks (20ms each) to keep during mute.
# 25 chunks = 500ms of audio to replay when assistant stops speaking.
STT_MUTE_BUFFER_CHUNKS = int(os.getenv("STT_MUTE_BUFFER_CHUNKS", "25"))
TRANSCRIPT_QUEUE_MAXSIZE = int(os.getenv("TRANSCRIPT_QUEUE_MAXSIZE", "32"))
PLAYBACK_QUEUE_MAXSIZE = int(os.getenv("PLAYBACK_QUEUE_MAXSIZE", "1024"))
TEXT_SEGMENT_QUEUE_MAXSIZE = int(os.getenv("TEXT_SEGMENT_QUEUE_MAXSIZE", "16"))


# ponytail: FILLER_TEXT_* and INITIAL_GREETING_TEXT were removed. They
# were hardcoded English/Spanish strings that masked the agent's
# welcome_message + dynamic prompts. Filler is now generated by
# the LLM adapter from session state; greeting comes from the agent row.
STREAMING_SEGMENT_MAX_CHARS = int(os.getenv("STREAMING_SEGMENT_MAX_CHARS", "200"))
STREAMING_FIRST_SEGMENT_CHARS = int(os.getenv("STREAMING_FIRST_SEGMENT_CHARS", "200"))
PARTIAL_TRANSCRIPT_START_CHARS = int(os.getenv("PARTIAL_TRANSCRIPT_START_CHARS", "20"))
PARTIAL_TRANSCRIPT_DEBOUNCE_MS = int(os.getenv("PARTIAL_TRANSCRIPT_DEBOUNCE_MS", "200"))
FINAL_RESTART_DELTA_CHARS = int(os.getenv("FINAL_RESTART_DELTA_CHARS", "12"))
PARTIAL_PREFETCH_MAX_DELTA_CHARS = int(os.getenv("PARTIAL_PREFETCH_MAX_DELTA_CHARS", "40"))
FINAL_TRANSCRIPT_GRACE_MS = int(os.getenv("FINAL_TRANSCRIPT_GRACE_MS", "800"))
DIGIT_DICTATION_GRACE_MS = int(os.getenv("DIGIT_DICTATION_GRACE_MS", "2000"))
SHORT_FINAL_MAX_WORDS = int(os.getenv("SHORT_FINAL_MAX_WORDS", "3"))
STT_RECONNECT_MAX_ATTEMPTS = int(os.getenv("STT_RECONNECT_MAX_ATTEMPTS", "3"))
STT_RECONNECT_BASE_DELAY_MS = int(os.getenv("STT_RECONNECT_BASE_DELAY_MS", "250"))
STT_RECONNECT_MAX_DELAY_MS = int(os.getenv("STT_RECONNECT_MAX_DELAY_MS", "2000"))
STT_FAILURE_PROMPT_EN = os.getenv("STT_FAILURE_PROMPT_EN", "I'm having trouble hearing you right now.").strip()
STT_FAILURE_PROMPT_ES = os.getenv("STT_FAILURE_PROMPT_ES", "Estoy teniendo problemas para escucharte en este momento.").strip()
IDLE_SILENCE_TIMEOUT_SEC = float(os.getenv("IDLE_SILENCE_TIMEOUT_SEC", "45"))

# ponytail: TWIML_INITIAL_GREETING_ENABLED/LANG removed entirely.
# Twilio's <Play> of a static greeting.wav was the root cause of the
# "two greetings on every call" bug — the static file played alongside
# the agent's welcome_message. Now the agent's welcome_message is the
# single source; if you want a pre-recorded greeting you can build it
# into the agent's welcome text and the TTS adapter will speak it.


# ponytail: per-minute pricing in USD. Two tiers:
# - own_key: the user is bringing their own provider credential, we just
#   charge a platform fee for running the orchestration.
# - platform_key: the user is using our provisioned credential, so the
#   provider cost is baked into our rate.
# Defaults are illustrative; tune via env when real billing lands.
PRICE_OWN_KEY_PER_MIN = float(os.getenv("PRICE_OWN_KEY_PER_MIN", "0.07"))
PRICE_PLATFORM_KEY_PER_MIN = float(os.getenv("PRICE_PLATFORM_KEY_PER_MIN", "0.14"))
